# -*- coding: utf-8 -*-
"""Assignement on diabetes data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWiTTF8WngLyWIse9WY-SQOLTbY-gcKY
"""



"""Assignment 1"""

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# read the data
df = pd.read_csv(r'/content/diabetes.csv')
df.head(5)

# display the coulmns
df.columns

# display the stastics/ mean of each coulmns
df.describe()

# checking the null values present in the data set
df.isnull()

#  check the null values
df.isnull().sum()

"""there is no null values present in the given data"""

# data visualization
plt.figure(figsize=(10,8))
sns.scatterplot(x='Glucose',y = 'Outcome',data = df,alpha = 0.5)
plt.xlabel('Glucose')
plt.ylabel('Outcome')
plt.title(' Glucose vs outcome')
plt.grid(True)
plt.show()

"""High glucose might impact on outcome"""

plt.figure(figsize=(8, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', center=0, linewidths=0.5, cbar_kws={'label': 'Correlation'})
plt.title("Correlation Map of Diabetic Variables")
plt.tight_layout()
plt.show()

"""According heat map glucose,bmi and age are related to the outcome"""

df.hist(bins=50, figsize=(20,15))
plt.show()



